// Select exactly one implementation.
// #include "02_Matrix_Multiplication_v0_naive.cu"
// #include "02_Matrix_Multiplication_v1_shared_memory.cu"
// #include "02_Matrix_Multiplication_v1_1d_thread_tiling.cu"
// #include "02_Matrix_Multiplication_v1_2d_thread_tiling.cu"
// #include "02_Matrix_Multiplication_v2_vectorized.cu"
// #include "02_Matrix_Multiplication_v2_vectorized_bk16.cu"
// #include "02_Matrix_Multiplication_v2_vectorized_large_tile.cu"
// #include "02_Matrix_Multiplication_v3_double_buffered.cu"
#include "02_Matrix_Multiplication_v3_large_tile.cu"
